### ISSUE TITLE
feat request: mul512x512

### ISSUE THREAD

**Issue by sandybradley** [SimonSuckut/Solidity_Uint512#3]
Hi Simon,
Thanks for publishing this lib. It's good. Any chance of adding a `mul512x512` function?

**Comment by SimonSuckut** [comment]
Hi [sandybradley](https://github.com/sandybradley)
Thanks for your request. The problem with mul512x512 is that the result is guaranteed to not fit in a 512 bit number, in fact it is a 1024 bit number. There are three possibilities:

* If you knwo that the result fits in a 512 bit number, at least one of the factors is less than 2^256 so you could use mul512x256 instead. 
* If you do not care about the overflow: Why do you need 512 bit multiplication? Consider using the ring properties of the mod 2^256 ring which is way cheaper to compute.
* If you really need 512x512 bit multiplication, the easiest (problably not the most gas efficient) way to implement it would be to apply the chinese remainder theoreme like it's done on the mul256x256 on 512 bit numbers.

Let me know if the described possiblities fixes your issue

**Comment by sandybradley** [comment]
Thanks for your feedback Simon. I got around this by simplifying my equation.
